/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsya3;

/**
 *
 * @author ZevusBloxk
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    String Name, Work;
    
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_Textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        occupation_Combobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textarea = new javax.swing.JTextArea();
        show_Button = new javax.swing.JButton();
        clear_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(name_Textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        jLabel2.setText("Work");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        occupation_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Collage", "Teacher", "Programer", "Analist" }));
        occupation_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupation_ComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(occupation_Combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        Textarea.setEditable(false);
        Textarea.setColumns(20);
        Textarea.setRows(5);
        jScrollPane1.setViewportView(Textarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 140));

        show_Button.setText("Show");
        show_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(show_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        clear_Button.setText("Clear");
        clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clear_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 60, -1));

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void occupation_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupation_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupation_ComboboxActionPerformed

    private void clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_ButtonActionPerformed
        // TODO add your handling code here:
        name_Textfield.setText("");
        Textarea.setText("");
    }//GEN-LAST:event_clear_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void show_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_ButtonActionPerformed
        // TODO add your handling code here:
        String name =name_Textfield.getText();
        if (name.equals("")) {
            Textarea.setText("Input Name First");
        }else{
                String occupation =(String) occupation_Combobox.getSelectedItem();
                Textarea.setText("Name: "+name+
                "\nOccupation: "+occupation);
        }
        
    }//GEN-LAST:event_show_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Textarea;
    private javax.swing.JButton clear_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_Textfield;
    private javax.swing.JComboBox<String> occupation_Combobox;
    private javax.swing.JButton show_Button;
    // End of variables declaration//GEN-END:variables
}
