/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsya3;

/**
 *
 * @author ZevusBloxk
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    String Name, Work;
    
    
    public Latihan3() {
        initComponents();
        food_List.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_Textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        show_Button = new javax.swing.JButton();
        clear_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        menu_list = new javax.swing.JTextField();
        food_List = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(name_Textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        jLabel2.setText("Favorite Food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        show_Button.setText("Show");
        show_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(show_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        clear_Button.setText("Clear");
        clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clear_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 60, -1));

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 60, -1));

        menu_list.setText("Food");
        menu_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_listMouseReleased(evt);
            }
        });
        menu_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listActionPerformed(evt);
            }
        });
        getContentPane().add(menu_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        food_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ramen", "Takoyaki", "Onigiri", "Udon", "Melon Pan" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        food_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        food_List.setAutoscrolls(false);
        food_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                food_ListMouseReleased(evt);
            }
        });
        getContentPane().add(food_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Textarea.setEditable(false);
        Textarea.setColumns(20);
        Textarea.setRows(5);
        jScrollPane1.setViewportView(Textarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_ButtonActionPerformed
        // TODO add your handling code here:
        name_Textfield.setText("");
        Textarea.setText("");
    }//GEN-LAST:event_clear_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void show_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_ButtonActionPerformed
        // TODO add your handling code here:
        String name =name_Textfield.getText();
        if (name.equals("")) {
            Textarea.setText("Input Name First");
        }else{
                

                Textarea.setText("Name: "+name+
                "\nFavorite Food: "+food_List.getSelectedValue());
        }
        
    }//GEN-LAST:event_show_ButtonActionPerformed

    private void food_ListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_food_ListMouseReleased
        // TODO add your handling code here:
        food_List.setVisible(false);
        menu_list.setVisible(true);
        menu_list.setText(food_List.getSelectedValue());
    }//GEN-LAST:event_food_ListMouseReleased

    private void menu_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menu_listActionPerformed

    private void menu_listMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_listMouseReleased
        // TODO add your handling code here:
        menu_list.setVisible(false);
        food_List.setVisible(true);
    }//GEN-LAST:event_menu_listMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Textarea;
    private javax.swing.JButton clear_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JList<String> food_List;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField menu_list;
    private javax.swing.JTextField name_Textfield;
    private javax.swing.JButton show_Button;
    // End of variables declaration//GEN-END:variables
}
