/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsya3;

import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author ZevusBloxk
 */
public class Tugas extends javax.swing.JFrame {

    /**
     * Creates new form Tugas
     */
    String background_toogle = "white"; 
    ImageIcon bg = new ImageIcon(getClass().getResource("/src/Netbean W Form.jpg"));
    String mcg ="";
    String genre = "";
    int xmouse;
    int ymouse;
    
    public Tugas() {
        initComponents();
        load_Layout();
        MaincharabuttonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void load_Layout(){
        background.setIcon(bg);
        close.setLocation(940, 10);
        close.setSize(50, 50);
        minimize.setLocation(830, 10);
        minimize.setSize(50, 50);
        switch_Theme.setLocation(720, 10);
        switch_Theme.setLocation(50, 50);
        drag.setLocation(0, 0);
        drag.setSize(1000, 50);
    }
    void MaincharabuttonGroup(){
        ButtonGroup mg = new ButtonGroup();
        mg.add(male_mc);
        mg.add(female_mc);
    }
    void genre(){
        if (action_genre.isSelected()) {
            genre = genre+" Action";
        }
        if (adventure_genre.isSelected()) {
            genre = genre+" Adventure";
        }
        if (comedy_genre.isSelected()) {
            genre = genre+" Comedy";
        }
        if (drama_genre.isSelected()) {
            genre = genre+" Drama";
        }
        if (ecchi_genre.isSelected()) {
            genre = genre+" Ecchi";
        }
        if (fantasy_genre.isSelected()) {
            genre = genre+" Fantasy";
        }
        if (horror_genre.isSelected()) {
            genre = genre+" Horror";
        }
        if (romance_genre.isSelected()) {
            genre = genre+" Romance";
        }
        if (school_genre.isSelected()) {
            genre = genre+" School";
        }
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        switch_Theme = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name_textfield = new javax.swing.JTextField();
        airing_label = new javax.swing.JLabel();
        airing_date_chooser = new com.toedter.calendar.JDateChooser();
        rating_label = new javax.swing.JLabel();
        rating_combobox = new javax.swing.JComboBox<>();
        mc_genter_label = new javax.swing.JLabel();
        male_mc = new javax.swing.JRadioButton();
        female_mc = new javax.swing.JRadioButton();
        genre_label = new javax.swing.JLabel();
        genre_list = new javax.swing.JPanel();
        action_genre = new javax.swing.JCheckBox();
        adventure_genre = new javax.swing.JCheckBox();
        comedy_genre = new javax.swing.JCheckBox();
        drama_genre = new javax.swing.JCheckBox();
        ecchi_genre = new javax.swing.JCheckBox();
        fantasy_genre = new javax.swing.JCheckBox();
        horror_genre = new javax.swing.JCheckBox();
        romance_genre = new javax.swing.JCheckBox();
        school_genre = new javax.swing.JCheckBox();
        reason_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reason_list = new javax.swing.JList<>();
        review_label = new javax.swing.JLabel();
        review_textarea = new javax.swing.JTextArea();
        Submit = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/src/Logo.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 50, 40));

        switch_Theme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                switch_ThemeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                switch_ThemeMouseReleased(evt);
            }
        });
        getContentPane().add(switch_Theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, 50));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 40));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        Header.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        Header.setText("Input Your Favorites Anime");
        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        name_label.setText("Name");
        getContentPane().add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(name_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, -1));

        airing_label.setText("Airing");
        getContentPane().add(airing_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        airing_date_chooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                airing_date_chooserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(airing_date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        rating_label.setText("Rating");
        getContentPane().add(rating_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        rating_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R - 17+", "PG - 13+", "PG  Childern" }));
        getContentPane().add(rating_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        mc_genter_label.setText("Main Character Gender");
        getContentPane().add(mc_genter_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        male_mc.setText("Male");
        male_mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_mcActionPerformed(evt);
            }
        });
        getContentPane().add(male_mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        female_mc.setText("Female");
        female_mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_mcActionPerformed(evt);
            }
        });
        getContentPane().add(female_mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        genre_label.setText("Genre");
        getContentPane().add(genre_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        genre_list.setBackground(new java.awt.Color(255, 255, 255));

        action_genre.setText("Action");

        adventure_genre.setText("Adventure");

        comedy_genre.setText("Comedy");

        drama_genre.setText("Drama");

        ecchi_genre.setText("Ecchi");

        fantasy_genre.setText("Fantasy");

        horror_genre.setText("Horror");

        romance_genre.setText("Romance");

        school_genre.setText("School");

        javax.swing.GroupLayout genre_listLayout = new javax.swing.GroupLayout(genre_list);
        genre_list.setLayout(genre_listLayout);
        genre_listLayout.setHorizontalGroup(
            genre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genre_listLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(genre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genre_listLayout.createSequentialGroup()
                        .addComponent(action_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drama_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horror_genre))
                    .addGroup(genre_listLayout.createSequentialGroup()
                        .addComponent(adventure_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ecchi_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(romance_genre))
                    .addGroup(genre_listLayout.createSequentialGroup()
                        .addComponent(comedy_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fantasy_genre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(school_genre)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        genre_listLayout.setVerticalGroup(
            genre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genre_listLayout.createSequentialGroup()
                .addGroup(genre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(action_genre)
                    .addComponent(drama_genre)
                    .addComponent(horror_genre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(genre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adventure_genre)
                    .addComponent(ecchi_genre)
                    .addComponent(romance_genre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(genre_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comedy_genre)
                    .addComponent(fantasy_genre)
                    .addComponent(school_genre))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        getContentPane().add(genre_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 280, 90));

        reason_label.setText("Reason u like it");
        getContentPane().add(reason_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        reason_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Good Story", "Good Ending", "Statisfying Ending", "Cool Main Character", "Lovable Heroine", "Nice Plot" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(reason_list);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 150, 100));

        review_label.setText("Overall Rewiews");
        getContentPane().add(review_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        review_textarea.setEditable(false);
        review_textarea.setColumns(20);
        review_textarea.setRows(5);
        getContentPane().add(review_textarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 360, 420));

        Submit.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Netbean W Form.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void switch_ThemeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_ThemeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_switch_ThemeMousePressed

    private void switch_ThemeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_ThemeMouseReleased
        // TODO add your handling code here:
        if (background_toogle == "white") {
            bg = new ImageIcon(getClass().getResource("/src/Netbean B Form.jpg"));
            background.setIcon(bg);
            background_toogle = "black";
        }else if (background_toogle == "black") {
            bg = new ImageIcon(getClass().getResource("/src/Netbean W Form.jpg"));
            background.setIcon(bg);
            background_toogle = "white";
        }
        
    }//GEN-LAST:event_switch_ThemeMouseReleased

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseReleased
        // TODO add your handling code here:
        genre = "";
        genre();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        if ((airing_date_chooser.getDate() == null 
                || name_textfield.equals("") 
                || rating_combobox.getSelectedItem() == null 
                ||genre.equals("")
                ||mcg.equals("")
                ||reason_list.getSelectedValuesList().equals(""))) {
            Validation_Menu vm = new Validation_Menu();
            vm.setVisible(true);
        }else{
            String airdate = df.format(airing_date_chooser.getDate());
            review_textarea.setText("Name "+name_textfield.getText()
                + "\nAiring Date "+airdate
                + "\nRating"+rating_combobox.getSelectedItem()
                + "\nGenre"+ genre
                + "\nMC Gender "+mcg
                + "\nReason "+reason_list.getSelectedValuesList());
        }
        
    }//GEN-LAST:event_SubmitMouseReleased

    private void male_mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_mcActionPerformed
        // TODO add your handling code here:
        mcg = "Male";
    }//GEN-LAST:event_male_mcActionPerformed

    private void female_mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_mcActionPerformed
        // TODO add your handling code here:
        mcg = "Female";
    }//GEN-LAST:event_female_mcActionPerformed

    private void airing_date_chooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_airing_date_chooserAncestorAdded
        // TODO add your handling code here:
//        System.exit(0);
    }//GEN-LAST:event_airing_date_chooserAncestorAdded

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        // TODO add your handling code here:
        this.setExtendedState(Tugas.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Submit;
    private javax.swing.JCheckBox action_genre;
    private javax.swing.JCheckBox adventure_genre;
    private com.toedter.calendar.JDateChooser airing_date_chooser;
    private javax.swing.JLabel airing_label;
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JCheckBox comedy_genre;
    private javax.swing.JLabel drag;
    private javax.swing.JCheckBox drama_genre;
    private javax.swing.JCheckBox ecchi_genre;
    private javax.swing.JCheckBox fantasy_genre;
    private javax.swing.JRadioButton female_mc;
    private javax.swing.JLabel genre_label;
    private javax.swing.JPanel genre_list;
    private javax.swing.JCheckBox horror_genre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male_mc;
    private javax.swing.JLabel mc_genter_label;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JComboBox<String> rating_combobox;
    private javax.swing.JLabel rating_label;
    private javax.swing.JLabel reason_label;
    private javax.swing.JList<String> reason_list;
    private javax.swing.JLabel review_label;
    private javax.swing.JTextArea review_textarea;
    private javax.swing.JCheckBox romance_genre;
    private javax.swing.JCheckBox school_genre;
    private javax.swing.JLabel switch_Theme;
    // End of variables declaration//GEN-END:variables
}
